name: Dispatch to dependents
on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      matrix:
        dependents: [Anyness, Math]
    name: Trigger Langulus::${{matrix.dependents}}'s workflow
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{secrets.TRIGGER_WORKFLOWS}}"
          https://api.github.com/repos/Langulus/${{matrix.dependents}}/dispatches
          -d '{"event_type":"Dependency changed"}'